import { useEffect } from 'react';
import { AnimationOnScroll } from 'react-animation-on-scroll';

import Head from "next/head";

import NavbarSecondary from "@/components/Navbar/NavbarSecondary";
import HeaderSecondary from '@/components/Header/HeaderSecondary'
import Description from "@/components/Description/Description";
import ServicesTabs from "@/components/Services/ServicesTabs";
import Questions from "@/components/Questions/Questions";
import Footer from "@/components/Footer/Footer";

export const getStaticProps = async () => {
    const [res1, res2, res3] = await Promise.all([
        fetch(`http://localhost:1337/api/global?populate=*`),
        fetch(`http://localhost:1337/api/services-page?populate=*`),
        fetch(`http://localhost:1337/api/services?populate=*`)
    ]);

    const [data1, data2, data3] = await Promise.all([
        res1.json(),
        res2.json(),
        res3.json()
    ])

    return {
        props: { global: data1, page: data2, services: data3 },
    }

};

const Services = ({ global, page, services }) => {
    useEffect(() => {
        window.scrollTo(0, 0)
      }, [])

    const title = page.data.attributes.title;
    const background = page.data.attributes.background.data.attributes;
    const descriptionTitle = page.data.attributes.descriptionTitle;
    const description = page.data.attributes.description;

    return (
        <>
            <Head>
                <title>Artea - web stuido</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <NavbarSecondary global={global} />

            <HeaderSecondary title={title} background={background} />

            <Description descriptionTitle={descriptionTitle} description={description} />

            <AnimationOnScroll animateIn="animate__fadeIn" animateOnce="true">
                <ServicesTabs services={services.data} />
            </AnimationOnScroll>

            <AnimationOnScroll animateIn="animate__fadeIn" animateOnce="true">
                <Questions />
            </AnimationOnScroll>

            <AnimationOnScroll animateIn="animate__fadeIn" animateOnce="true">
                <Footer global={global} />
            </AnimationOnScroll>
        </>
    )
};

export default Services;