import Head from "next/head";
import Error from "@/components/Error/Error"

function timer(time, domain) {
    var timer = setInterval(function () {
        if (time <= 0) {
            clearInterval(timer);
            document.location = domain;
        } else {
            time--;
        }
    }, time)
}

const Success = () => {
    timer(10, "/");
    return (
        <div>
            <Head>
                <title>Artea - web stuido</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Error
                errorCode={`Отправлено`}
                errorName={``}
                errorText={``}
            />

        </div>
    )
}

export default Success;